// lib/mock-data.ts
// Catálogo de autos cotidianos (sedanes, compactos, SUVs familiares).
// Fotografías laterales nítidas sobre fondo neutro, especificaciones técnicas concretas.

import { type Vehicle } from '@/types/vehicle'

export const MOCK_VEHICLES: Vehicle[] = [
  {
    id: '1',
    slug: 'toyota-yaris-2024-blanco',
    brand: 'Toyota',
    model: 'Yaris Sedán',
    year: 2024,
    category: 'sedan',
    transmission: 'automatic',
    fuel: 'gasoline',
    seats: 5,
    luggage: 2,
    daily_rate: 35,
    sale_price: 18900,
    mileage: 9100,
    color: 'Blanco Puro',
    fuel_consumption: '18.5 km/l',
    suitability_tag: 'Uso diario',
    trip_type: 'city',
    features: ['Aire acondicionado digital', 'Pantalla táctil 7" Apple CarPlay', 'Cámara de reversa', 'Frenos ABS + EBD', 'Maletero 475L'],
    images: [
      'https://images.unsplash.com/photo-1590362891991-f776e747a588?w=1200&q=80',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1590362891991-f776e747a588?w=800&q=80',
    description: 'Sedán cotidiano por excelencia. Mecánica confiable, marcha suave y consumo reducido para traslados urbanos y diligencias.',
    status: 'available',
    is_featured: true,
    sort_order: 1,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '2',
    slug: 'nissan-versa-2024-gris',
    brand: 'Nissan',
    model: 'Versa Sense',
    year: 2024,
    category: 'sedan',
    transmission: 'manual',
    fuel: 'gasoline',
    seats: 5,
    luggage: 2,
    daily_rate: 34,
    sale_price: 18500,
    mileage: 10500,
    color: 'Gris Grafito',
    fuel_consumption: '18.0 km/l',
    suitability_tag: 'Bajo consumo',
    trip_type: 'city',
    features: ['6 bolsas de aire de serie', 'Frenado autónomo de emergencia', 'Bluetooth y mandos al volante', 'Asistente de ascenso en pendiente'],
    images: [
      'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=1200&q=80',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=800&q=80',
    description: 'Sedán espacioso en plazas traseras con excelente equipamiento de seguridad activa y gran rendimiento de combustible.',
    status: 'available',
    is_featured: true,
    sort_order: 2,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '3',
    slug: 'toyota-corolla-2024-plata',
    brand: 'Toyota',
    model: 'Corolla 2.0',
    year: 2024,
    category: 'sedan',
    transmission: 'automatic',
    fuel: 'gasoline',
    seats: 5,
    luggage: 3,
    daily_rate: 42,
    sale_price: 24500,
    mileage: 12000,
    color: 'Plata Metálico',
    fuel_consumption: '17.2 km/l',
    suitability_tag: 'Confort carretera',
    trip_type: 'roadtrip',
    features: ['Toyota Safety Sense', 'Control crucero adaptativo', 'Apple CarPlay & Android Auto', 'Maletero de 470 litros', 'Faros Bi-LED'],
    images: [
      'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=1200&q=80',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800&q=80',
    description: 'El sedán mediano más probado del mercado. Estabilidad impecable en autopista, excelente insonorización y amplio maletero.',
    status: 'available',
    is_featured: true,
    sort_order: 3,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '4',
    slug: 'hyundai-tucson-2024-gris',
    brand: 'Hyundai',
    model: 'Tucson 2.0',
    year: 2024,
    category: 'suv',
    transmission: 'automatic',
    fuel: 'gasoline',
    seats: 5,
    luggage: 3,
    daily_rate: 54,
    sale_price: 29800,
    mileage: 9500,
    color: 'Gris Titanio',
    fuel_consumption: '14.2 km/l',
    suitability_tag: 'Familiar espacioso',
    trip_type: 'roadtrip',
    features: ['Maletero de 540L', 'Cámara de reversa HD', 'Asistente de arranque en pendiente', 'Climatizador bi-zona', 'Barras de techo'],
    images: [
      'https://images.unsplash.com/photo-1600661653561-629509216228?w=1200&q=80',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1600661653561-629509216228?w=800&q=80',
    description: 'SUV espaciosa ideal para viajes en familia. Asientos traseros reclinables, piso plano y capacidad de carga generosa.',
    status: 'available',
    is_featured: true,
    sort_order: 4,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '5',
    slug: 'kia-soluto-2024-blanco',
    brand: 'Kia',
    model: 'Soluto LX',
    year: 2024,
    category: 'sedan',
    transmission: 'manual',
    fuel: 'gasoline',
    seats: 5,
    luggage: 2,
    daily_rate: 29,
    sale_price: 15900,
    mileage: 16000,
    color: 'Blanco',
    fuel_consumption: '18.4 km/l',
    suitability_tag: 'Económico urbano',
    trip_type: 'city',
    features: ['Pantalla táctil 7" Bluetooth', 'Dirección asistida eléctrica', 'Aire acondicionado', 'Frenos ABS', 'Anclajes ISOFIX'],
    images: [
      'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=1200&q=80',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=800&q=80',
    description: 'La opción más económica y práctica para movilidad cotidiana sin complicaciones mecánicas.',
    status: 'available',
    is_featured: false,
    sort_order: 5,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '6',
    slug: 'suzuki-swift-2024-rojo',
    brand: 'Suzuki',
    model: 'Swift GLX',
    year: 2024,
    category: 'sport',
    transmission: 'manual',
    fuel: 'gasoline',
    seats: 5,
    luggage: 2,
    daily_rate: 32,
    sale_price: 17800,
    mileage: 11000,
    color: 'Rojo Carmesí',
    fuel_consumption: '19.8 km/l',
    suitability_tag: 'Ultracompacto',
    trip_type: 'city',
    features: ['Fácil aparcamiento en ciudad', 'Pantalla táctil 9"', '6 airbags', 'Consumo ultra bajo', 'Volante forrado en cuero'],
    images: [
      'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=1200&q=80',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&q=80',
    description: 'Hatchback compacto y ágil para el tráfico diario. Cabe en cualquier estacionamiento y reduce al mínimo el gasto de combustible.',
    status: 'available',
    is_featured: false,
    sort_order: 6,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '7',
    slug: 'nissan-kicks-2024-azul',
    brand: 'Nissan',
    model: 'Kicks Advance',
    year: 2024,
    category: 'suv',
    transmission: 'automatic',
    fuel: 'gasoline',
    seats: 5,
    luggage: 3,
    daily_rate: 46,
    sale_price: 23900,
    mileage: 8000,
    color: 'Azul Zafiro',
    fuel_consumption: '16.5 km/l',
    suitability_tag: 'Crossover versátil',
    trip_type: 'weekend',
    features: ['Despeje al suelo 20 cm', 'Asientos Zero Gravity', 'Apple CarPlay & Android Auto', 'Sensores de reversa', 'Control de estabilidad'],
    images: [
      'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=1200&q=80',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&q=80',
    description: 'Crossover cómodo y elevado para evitar baches en la ciudad o salir a caminos rurales ligeros durante el fin de semana.',
    status: 'available',
    is_featured: false,
    sort_order: 7,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '8',
    slug: 'chevrolet-tracker-2024-negro',
    brand: 'Chevrolet',
    model: 'Tracker Turbo',
    year: 2024,
    category: 'suv',
    transmission: 'automatic',
    fuel: 'gasoline',
    seats: 5,
    luggage: 3,
    daily_rate: 48,
    sale_price: 25400,
    mileage: 7200,
    color: 'Negro Ónix',
    fuel_consumption: '15.6 km/l',
    suitability_tag: 'Familiar dinámico',
    trip_type: 'weekend',
    features: ['Motor 1.2L Turbo', '6 airbags de serie', 'Pantalla MyLink 8"', 'Control de tracción', 'Cámara de reversa'],
    images: [
      'https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?w=1200&q=80',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?w=800&q=80',
    description: 'SUV compacta con respuesta ágil para rebasar en carretera y amplio espacio interior para 5 ocupantes.',
    status: 'available',
    is_featured: false,
    sort_order: 8,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '9',
    slug: 'volkswagen-polo-2024-gris',
    brand: 'Volkswagen',
    model: 'Polo Track',
    year: 2024,
    category: 'sport',
    transmission: 'manual',
    fuel: 'gasoline',
    seats: 5,
    luggage: 2,
    daily_rate: 30,
    sale_price: 16500,
    mileage: 6500,
    color: 'Gris Platino',
    fuel_consumption: '18.1 km/l',
    suitability_tag: 'Urbano robusto',
    trip_type: 'city',
    features: ['Suspensión reforzada Track', '4 airbags frontales y laterales', 'Aire acondicionado', 'Control de estabilidad ESP', 'Asistente de arranque'],
    images: [
      'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=1200&q=80',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=800&q=80',
    description: 'Compacto firme y resistente para el asfalto diario. Bajo consumo y construcción sólida alemana.',
    status: 'available',
    is_featured: false,
    sort_order: 9,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '10',
    slug: 'toyota-hilux-2024-blanco',
    brand: 'Toyota',
    model: 'Hilux Doble Cabina 4x4',
    year: 2024,
    category: 'pickup_4x4',
    transmission: 'manual',
    fuel: 'diesel',
    seats: 5,
    luggage: 4,
    daily_rate: 68,
    sale_price: 36000,
    mileage: 14000,
    color: 'Blanco',
    fuel_consumption: '12.8 km/l',
    suitability_tag: 'Apto montaña / campo',
    trip_type: 'roadtrip',
    features: ['Tracción 4x4 con reductora', 'Bloqueo diferencial trasero', 'Tolva de carga 1T', 'Protector de balde', 'Control de descenso'],
    images: [
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&q=80',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    description: 'Camioneta 4x4 para caminos no asfaltados, ripio, montaña o transporte de carga pesada.',
    status: 'available',
    is_featured: false,
    sort_order: 10,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '11',
    slug: 'renault-duster-2024-naranja',
    brand: 'Renault',
    model: 'Duster 4x4',
    year: 2024,
    category: 'suv',
    transmission: 'manual',
    fuel: 'gasoline',
    seats: 5,
    luggage: 3,
    daily_rate: 49,
    sale_price: 24900,
    mileage: 10500,
    color: 'Naranja Atacama',
    fuel_consumption: '13.9 km/l',
    suitability_tag: 'Apto ripio',
    trip_type: 'roadtrip',
    features: ['Tracción 4x4 con selector', 'Despeje al suelo 21 cm', 'Barras de techo funcionales', 'Protecciones de carrocería'],
    images: [
      'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=1200&q=80',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&q=80',
    description: 'SUV accesible con capacidades reales para caminos de lastre y carreteras secundarias.',
    status: 'available',
    is_featured: false,
    sort_order: 11,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '12',
    slug: 'kia-sportage-2024-blanco',
    brand: 'Kia',
    model: 'Sportage Active',
    year: 2024,
    category: 'suv',
    transmission: 'automatic',
    fuel: 'gasoline',
    seats: 5,
    luggage: 3,
    daily_rate: 52,
    sale_price: 28900,
    mileage: 8900,
    color: 'Blanco Claro',
    fuel_consumption: '14.8 km/l',
    suitability_tag: 'Familiar espacioso',
    trip_type: 'roadtrip',
    features: ['Cabina espaciosa para 5 personas', 'Pantalla táctil panorámica', 'Freno de mano eléctrico', 'Maletero 591L'],
    images: [
      'https://images.unsplash.com/photo-1600661653561-629509216228?w=1200&q=80',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1600661653561-629509216228?w=800&q=80',
    description: 'SUV de rodaje silencioso y amplio volumen para equipaje en trayectos largos.',
    status: 'available',
    is_featured: false,
    sort_order: 12,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
]

// ── CRUD Helpers para Desarrollo / Mock Store ───────────────────────────────

export function getMockVehicles(): Vehicle[] {
  return [...MOCK_VEHICLES]
}

export function findMockVehicleById(id: string): Vehicle | undefined {
  return MOCK_VEHICLES.find((v) => v.id === id)
}

export function addMockVehicle(newVehicle: Vehicle): Vehicle {
  MOCK_VEHICLES.unshift(newVehicle)
  return newVehicle
}

export function updateMockVehicle(id: string, updates: Partial<Vehicle>): Vehicle | null {
  const index = MOCK_VEHICLES.findIndex((v) => v.id === id)
  if (index === -1) return null

  MOCK_VEHICLES[index] = {
    ...MOCK_VEHICLES[index],
    ...updates,
    updated_at: new Date().toISOString(),
  }
  return MOCK_VEHICLES[index]
}

export function deleteMockVehicle(id: string): boolean {
  const index = MOCK_VEHICLES.findIndex((v) => v.id === id)
  if (index === -1) return false
  MOCK_VEHICLES.splice(index, 1)
  return true
}

export function updateMockVehicleStatus(id: string, status: Vehicle['status']): Vehicle | null {
  return updateMockVehicle(id, { status })
}
